//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mytimesaver.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Mytimesaver.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // grades are mandatory
        ///var grades = /*grades*/;
        ///// comments are optional
        ////*comments*/
        ///
        ///var form = document.forms.namedItem(&quot;Form2&quot;);
        ///
        ///for (var kt in grades)
        ///{
        ///	console.log(&apos;Setting grade: &apos;+kt)
        ///	var grade = form.elements.namedItem(&quot;grade&quot;+kt);
        ///	grade.value = grades[kt];
        ///	if (typeof(comments) != &apos;undefined&apos; &amp;&amp; kt in comments)
        ///	{
        ///		var memo = form.elements.namedItem(&quot;memo&quot;+kt);
        ///		memo.value = comments[kt];
        ///	}
        ///}.
        /// </summary>
        internal static string AssignmentTemplate {
            get {
                return ResourceManager.GetString("AssignmentTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to var grades = /*grades*/;
        ///
        ///for (var kt in grades)
        ///{
        ///	console.log(&apos;Setting grade: &apos;+kt)
        ///	var select = document.getElementById(&quot;g&quot;+kt);
        ///	for(j = 0; j != select.options.length; j++)
        ///	{
        ///		if(select.options[j].value == grades[kt])
        ///		{
        ///			select.options[j].selected = true;
        ///			break;
        ///		}
        ///	}
        ///}.
        /// </summary>
        internal static string FinalTemplate {
            get {
                return ResourceManager.GetString("FinalTemplate", resourceCulture);
            }
        }
    }
}
